### ISSUE TITLE
Searching on an 8GB GPU

### ISSUE THREAD

**Issue by deepseek** [DrSleep/nas-segm-pytorch#4]
@DrSleep 

What configurations should be made in-order to search and train on a single 8gb gpu

**Comment by DrSleep** [comment]
I don't really know. You can try to reduce the batch size and/or crop-size (and potentially `N_TASK0', which is the number of examples kept in the memory during the first search stage) [here](https://github.com/DrSleep/nas-segm-pytorch/blob/master/src/utils/default_args.py) until sampled architectures fit into your budget and can be run without any errors. Then you would need to experiment primarily with the learning rates of the encoder and the decoder until several sampled architectures achieve somewhat decent performance
